# Generated by Django 4.2.7 on 2023-11-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_sectionproject_position'),
        ('task', '0011_rename_userpositiontask_userleveltask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='section_project',
        ),
        migrations.CreateModel(
            name='TaskToSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в секцию')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('section_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.sectionproject', verbose_name='Этап в проекте')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Задача к Секции',
                'verbose_name_plural': 'Задачи к Секциям',
            },
        ),
    ]
