# Generated by Django 4.2.7 on 2023-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_remove_task_section_project_tasktosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttask',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='subtaskchecklist',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='tasktosection',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Позиция'),
        ),
    ]
