# Generated by Django 4.2.7 on 2023-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionproject',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
    ]
