# Generated by Django 4.2.7 on 2023-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_sectionproject_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionproject',
            name='position',
            field=models.IntegerField(default=-1, verbose_name='Позиция'),
        ),
    ]
