# Generated by Django 4.2.7 on 2023-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_sectionproject_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionproject',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Позиция'),
        ),
    ]
