# Generated by Django 3.2.23 on 2024-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_sectionproject_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionproject',
            name='hex',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Цвет'),
        ),
    ]
