# Generated by Django 3.2.23 on 2024-03-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color'),
        ('project', '0011_sectionproject_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionproject',
            name='hex',
        ),
        migrations.AddField(
            model_name='sectionproject',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color', verbose_name='Цвет'),
        ),
    ]
