# Generated by Django 4.2.7 on 2023-11-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
